<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>TRACE;FANTASY_NET</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>TRACE;FANTASY_NET</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);DebugFantasySG</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Server\Fantasy.Packages\Fantasy.Net\Fantasy.Net.csproj" AdditionalProperties="TargetFramework=net8.0;TargetFrameworks=net8.0" />
    <ProjectReference Include="..\..\..\Server\Fantasy.Packages\Fantasy.SourceGenerator\Fantasy.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Protocol\Generated\Server\*.cs" Link="Generate\NetworkProtocol\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Fantasy.config" />
    <AdditionalFiles Include="Fantasy.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AdditionalFiles>
    <None Include="..\..\..\Server\Fantasy.Packages\Fantasy.Net\Fantasy.xsd" Link="Fantasy.xsd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
