
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EnemyKey = _buf.ReadString();
        Name = _buf.ReadString();
        ModelPath = _buf.ReadString();
        BaseHp = _buf.ReadFloat();
        BaseAttack = _buf.ReadFloat();
        BaseDefense = _buf.ReadFloat();
        BaseExp = _buf.ReadInt();
        MoveSpeed = _buf.ReadFloat();
        AttackRange = _buf.ReadFloat();
        AttackInterval = _buf.ReadFloat();
        AggroRadius = _buf.ReadFloat();
        MovePriority = _buf.ReadInt();
        TemplateKey = _buf.ReadString();
        VisualScale = _buf.ReadFloat();
    }

    public static Enemy DeserializeEnemy(ByteBuf _buf)
    {
        return new stage.Enemy(_buf);
    }

    /// <summary>
    /// Enemy id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Program key.
    /// </summary>
    public readonly string EnemyKey;
    /// <summary>
    /// Display name.
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Prefab path.
    /// </summary>
    public readonly string ModelPath;
    /// <summary>
    /// Base hp.
    /// </summary>
    public readonly float BaseHp;
    /// <summary>
    /// Base attack.
    /// </summary>
    public readonly float BaseAttack;
    /// <summary>
    /// Base defense.
    /// </summary>
    public readonly float BaseDefense;
    /// <summary>
    /// Base exp reward.
    /// </summary>
    public readonly int BaseExp;
    /// <summary>
    /// Move speed.
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// Attack range.
    /// </summary>
    public readonly float AttackRange;
    /// <summary>
    /// Attack interval.
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// Aggro radius.
    /// </summary>
    public readonly float AggroRadius;
    /// <summary>
    /// Move priority.
    /// </summary>
    public readonly int MovePriority;
    /// <summary>
    /// Local template key.
    /// </summary>
    public readonly string TemplateKey;
    /// <summary>
    /// Visual scale.
    /// </summary>
    public readonly float VisualScale;
   
    public const int __ID__ = -1092691848;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "enemyKey:" + EnemyKey + ","
        + "name:" + Name + ","
        + "modelPath:" + ModelPath + ","
        + "baseHp:" + BaseHp + ","
        + "baseAttack:" + BaseAttack + ","
        + "baseDefense:" + BaseDefense + ","
        + "baseExp:" + BaseExp + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "attackRange:" + AttackRange + ","
        + "attackInterval:" + AttackInterval + ","
        + "aggroRadius:" + AggroRadius + ","
        + "movePriority:" + MovePriority + ","
        + "templateKey:" + TemplateKey + ","
        + "visualScale:" + VisualScale + ","
        + "}";
    }
}
}

