
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
public sealed partial class EnemyLevel : Luban.BeanBase
{
    public EnemyLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EnemyId = _buf.ReadInt();
        Level = _buf.ReadInt();
        HpMultiplier = _buf.ReadFloat();
        AttackMultiplier = _buf.ReadFloat();
        DefenseMultiplier = _buf.ReadFloat();
        ExpMultiplier = _buf.ReadFloat();
        GoldMultiplier = _buf.ReadFloat();
    }

    public static EnemyLevel DeserializeEnemyLevel(ByteBuf _buf)
    {
        return new stage.EnemyLevel(_buf);
    }

    /// <summary>
    /// Enemy level row id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Enemy id.
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// Enemy level.
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// Hp multiplier.
    /// </summary>
    public readonly float HpMultiplier;
    /// <summary>
    /// Attack multiplier.
    /// </summary>
    public readonly float AttackMultiplier;
    /// <summary>
    /// Defense multiplier.
    /// </summary>
    public readonly float DefenseMultiplier;
    /// <summary>
    /// Exp multiplier.
    /// </summary>
    public readonly float ExpMultiplier;
    /// <summary>
    /// Gold multiplier.
    /// </summary>
    public readonly float GoldMultiplier;
   
    public const int __ID__ = 1137466860;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "enemyId:" + EnemyId + ","
        + "level:" + Level + ","
        + "hpMultiplier:" + HpMultiplier + ","
        + "attackMultiplier:" + AttackMultiplier + ","
        + "defenseMultiplier:" + DefenseMultiplier + ","
        + "expMultiplier:" + ExpMultiplier + ","
        + "goldMultiplier:" + GoldMultiplier + ","
        + "}";
    }
}
}

