
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
public sealed partial class HeroLevel : Luban.BeanBase
{
    public HeroLevel(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        HeroId = _buf.ReadInt();
        Level = _buf.ReadInt();
        RequiredExp = _buf.ReadInt();
        HpMultiplier = _buf.ReadFloat();
        AttackMultiplier = _buf.ReadFloat();
        DefenseMultiplier = _buf.ReadFloat();
        MaxResourceBonus = _buf.ReadFloat();
    }

    public static HeroLevel DeserializeHeroLevel(ByteBuf _buf)
    {
        return new stage.HeroLevel(_buf);
    }

    /// <summary>
    /// Hero level row id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Hero id.
    /// </summary>
    public readonly int HeroId;
    /// <summary>
    /// Level.
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// Required exp to reach this level.
    /// </summary>
    public readonly int RequiredExp;
    /// <summary>
    /// Hp multiplier.
    /// </summary>
    public readonly float HpMultiplier;
    /// <summary>
    /// Attack multiplier.
    /// </summary>
    public readonly float AttackMultiplier;
    /// <summary>
    /// Defense multiplier.
    /// </summary>
    public readonly float DefenseMultiplier;
    /// <summary>
    /// Max resource bonus.
    /// </summary>
    public readonly float MaxResourceBonus;
   
    public const int __ID__ = -788473702;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "heroId:" + HeroId + ","
        + "level:" + Level + ","
        + "requiredExp:" + RequiredExp + ","
        + "hpMultiplier:" + HpMultiplier + ","
        + "attackMultiplier:" + AttackMultiplier + ","
        + "defenseMultiplier:" + DefenseMultiplier + ","
        + "maxResourceBonus:" + MaxResourceBonus + ","
        + "}";
    }
}
}

