
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
public sealed partial class Hero : Luban.BeanBase
{
    public Hero(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        HeroKey = _buf.ReadString();
        Name = _buf.ReadString();
        ClassType = _buf.ReadString();
        BaseHp = _buf.ReadFloat();
        BaseAttack = _buf.ReadFloat();
        BaseDefense = _buf.ReadFloat();
        MoveSpeed = _buf.ReadFloat();
        AttackRange = _buf.ReadFloat();
        AttackInterval = _buf.ReadFloat();
        AggroRadius = _buf.ReadFloat();
        HealthRegen = _buf.ReadFloat();
        ResourceType = _buf.ReadString();
        MaxResource = _buf.ReadFloat();
        InitialResource = _buf.ReadFloat();
        ResourceRegen = _buf.ReadFloat();
        MovePriority = _buf.ReadInt();
        DefaultSkillIds = _buf.ReadString();
        BarPrefabType = _buf.ReadString();
    }

    public static Hero DeserializeHero(ByteBuf _buf)
    {
        return new stage.Hero(_buf);
    }

    /// <summary>
    /// Hero id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Program key.
    /// </summary>
    public readonly string HeroKey;
    /// <summary>
    /// Display name.
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Class type.
    /// </summary>
    public readonly string ClassType;
    /// <summary>
    /// Base hp.
    /// </summary>
    public readonly float BaseHp;
    /// <summary>
    /// Base attack.
    /// </summary>
    public readonly float BaseAttack;
    /// <summary>
    /// Base defense.
    /// </summary>
    public readonly float BaseDefense;
    /// <summary>
    /// Move speed.
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// Attack range.
    /// </summary>
    public readonly float AttackRange;
    /// <summary>
    /// Attack interval.
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// Aggro radius.
    /// </summary>
    public readonly float AggroRadius;
    /// <summary>
    /// Health regen per second.
    /// </summary>
    public readonly float HealthRegen;
    /// <summary>
    /// Resource type.
    /// </summary>
    public readonly string ResourceType;
    /// <summary>
    /// Max resource.
    /// </summary>
    public readonly float MaxResource;
    /// <summary>
    /// Initial resource.
    /// </summary>
    public readonly float InitialResource;
    /// <summary>
    /// Resource regen per second.
    /// </summary>
    public readonly float ResourceRegen;
    /// <summary>
    /// Move priority.
    /// </summary>
    public readonly int MovePriority;
    /// <summary>
    /// Comma separated default skill ids.
    /// </summary>
    public readonly string DefaultSkillIds;
    /// <summary>
    /// World bar prefab type.
    /// </summary>
    public readonly string BarPrefabType;
   
    public const int __ID__ = 1073211658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "heroKey:" + HeroKey + ","
        + "name:" + Name + ","
        + "classType:" + ClassType + ","
        + "baseHp:" + BaseHp + ","
        + "baseAttack:" + BaseAttack + ","
        + "baseDefense:" + BaseDefense + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "attackRange:" + AttackRange + ","
        + "attackInterval:" + AttackInterval + ","
        + "aggroRadius:" + AggroRadius + ","
        + "healthRegen:" + HealthRegen + ","
        + "resourceType:" + ResourceType + ","
        + "maxResource:" + MaxResource + ","
        + "initialResource:" + InitialResource + ","
        + "resourceRegen:" + ResourceRegen + ","
        + "movePriority:" + MovePriority + ","
        + "defaultSkillIds:" + DefaultSkillIds + ","
        + "barPrefabType:" + BarPrefabType + ","
        + "}";
    }
}
}

