
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
public sealed partial class Stage : Luban.BeanBase
{
    public Stage(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        StageKey = _buf.ReadString();
        Name = _buf.ReadString();
        RouteKey = _buf.ReadString();
        LoopMode = _buf.ReadString();
        FirstWaveIndex = _buf.ReadInt();
    }

    public static Stage DeserializeStage(ByteBuf _buf)
    {
        return new stage.Stage(_buf);
    }

    /// <summary>
    /// Stage id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Program key.
    /// </summary>
    public readonly string StageKey;
    /// <summary>
    /// Display name.
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Route key.
    /// </summary>
    public readonly string RouteKey;
    /// <summary>
    /// Loop mode.
    /// </summary>
    public readonly string LoopMode;
    /// <summary>
    /// First wave index.
    /// </summary>
    public readonly int FirstWaveIndex;
   
    public const int __ID__ = -1079587858;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "stageKey:" + StageKey + ","
        + "name:" + Name + ","
        + "routeKey:" + RouteKey + ","
        + "loopMode:" + LoopMode + ","
        + "firstWaveIndex:" + FirstWaveIndex + ","
        + "}";
    }
}
}

