
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
/// <summary>
/// Enemy base config.
/// </summary>
public partial class TbEnemy
{
    private readonly System.Collections.Generic.Dictionary<int, stage.Enemy> _dataMap;
    private readonly System.Collections.Generic.List<stage.Enemy> _dataList;
    
    public TbEnemy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, stage.Enemy>(n);
        _dataList = new System.Collections.Generic.List<stage.Enemy>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stage.Enemy _v;
            _v = global::GameConfig.stage.Enemy.DeserializeEnemy(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, stage.Enemy> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stage.Enemy> DataList => _dataList;

    public stage.Enemy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stage.Enemy Get(int key) => _dataMap[key];
    public stage.Enemy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

