
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
/// <summary>
/// Hero level growth config.
/// </summary>
public partial class TbHeroLevel
{
    private readonly System.Collections.Generic.Dictionary<int, stage.HeroLevel> _dataMap;
    private readonly System.Collections.Generic.List<stage.HeroLevel> _dataList;
    
    public TbHeroLevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, stage.HeroLevel>(n);
        _dataList = new System.Collections.Generic.List<stage.HeroLevel>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stage.HeroLevel _v;
            _v = global::GameConfig.stage.HeroLevel.DeserializeHeroLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, stage.HeroLevel> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stage.HeroLevel> DataList => _dataList;

    public stage.HeroLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stage.HeroLevel Get(int key) => _dataMap[key];
    public stage.HeroLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

