
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stage
{
public sealed partial class Wave : Luban.BeanBase
{
    public Wave(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        StageId = _buf.ReadInt();
        WaveIndex = _buf.ReadInt();
        SpawnMode = _buf.ReadString();
        EnemyId = _buf.ReadInt();
        EnemyLevel = _buf.ReadInt();
        Count = _buf.ReadInt();
        SpawnDistanceAhead = _buf.ReadFloat();
        SpawnRadius = _buf.ReadFloat();
        SpawnAnchorId = _buf.ReadString();
        IsBoss = _buf.ReadInt();
        NextWaveDelay = _buf.ReadFloat();
        SpawnEngageMode = _buf.ReadString();
    }

    public static Wave DeserializeWave(ByteBuf _buf)
    {
        return new stage.Wave(_buf);
    }

    /// <summary>
    /// Wave id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Stage id.
    /// </summary>
    public readonly int StageId;
    /// <summary>
    /// Wave index.
    /// </summary>
    public readonly int WaveIndex;
    /// <summary>
    /// Spawn mode.
    /// </summary>
    public readonly string SpawnMode;
    /// <summary>
    /// Enemy id.
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// Enemy level.
    /// </summary>
    public readonly int EnemyLevel;
    /// <summary>
    /// Enemy count.
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// Distance ahead.
    /// </summary>
    public readonly float SpawnDistanceAhead;
    /// <summary>
    /// Spawn radius.
    /// </summary>
    public readonly float SpawnRadius;
    /// <summary>
    /// Fixed anchor id.
    /// </summary>
    public readonly string SpawnAnchorId;
    /// <summary>
    /// Is boss 1 or 0.
    /// </summary>
    public readonly int IsBoss;
    /// <summary>
    /// Next wave delay.
    /// </summary>
    public readonly float NextWaveDelay;
    /// <summary>
    /// Spawn engage mode: RushTeam or HoldPosition.
    /// </summary>
    public readonly string SpawnEngageMode;
   
    public const int __ID__ = 1073654793;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "stageId:" + StageId + ","
        + "waveIndex:" + WaveIndex + ","
        + "spawnMode:" + SpawnMode + ","
        + "enemyId:" + EnemyId + ","
        + "enemyLevel:" + EnemyLevel + ","
        + "count:" + Count + ","
        + "spawnDistanceAhead:" + SpawnDistanceAhead + ","
        + "spawnRadius:" + SpawnRadius + ","
        + "spawnAnchorId:" + SpawnAnchorId + ","
        + "isBoss:" + IsBoss + ","
        + "nextWaveDelay:" + NextWaveDelay + ","
        + "spawnEngageMode:" + SpawnEngageMode + ","
        + "}";
    }
}
}

