<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <OutputPath>../../../Bin/Debug/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>../../../Bin/Release/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entity\IDRPG3D.GameServer.Entity.csproj" />
    <ProjectReference Include="..\Hotfix\IDRPG3D.GameServer.Hotfix.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.8.0" />
  </ItemGroup>
</Project>
