
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Buff : Luban.BeanBase
{
    public Buff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BuffKey = _buf.ReadString();
        Name = _buf.ReadString();
        BuffType = _buf.ReadString();
        Duration = _buf.ReadFloat();
        MaxStack = _buf.ReadInt();
        TickInterval = _buf.ReadFloat();
        StatType = _buf.ReadString();
        ModifierType = _buf.ReadString();
        ModifierValue = _buf.ReadFloat();
        ControlFlags = _buf.ReadString();
        AuraRadius = _buf.ReadFloat();
    }

    public static Buff DeserializeBuff(ByteBuf _buf)
    {
        return new skill.Buff(_buf);
    }

    /// <summary>
    /// Buff ID。0固定表示没有Buff。
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff Key。程序识别用。
    /// </summary>
    public readonly string BuffKey;
    /// <summary>
    /// Buff显示名。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Buff类型。None/Dot/Hot/StatModifier/Control/Aura 等。
    /// </summary>
    public readonly string BuffType;
    /// <summary>
    /// 持续时间，单位秒。0表示无持续时间。
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 最大叠层。0或1表示不可叠加；大于1表示可叠层。
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 跳频，单位秒。持续伤害/治疗每隔多久结算一次。
    /// </summary>
    public readonly float TickInterval;
    /// <summary>
    /// 影响的属性。None/Attack/MoveSpeed/CastSpeed 等。
    /// </summary>
    public readonly string StatType;
    /// <summary>
    /// 修改方式。None/Add/Percent/Mul 等。
    /// </summary>
    public readonly string ModifierType;
    /// <summary>
    /// 修改值。比如移速-30%可填 -0.3。
    /// </summary>
    public readonly float ModifierValue;
    /// <summary>
    /// 控制标记。None/Stun/Silence/Root 等，可用逗号组合。
    /// </summary>
    public readonly string ControlFlags;
    /// <summary>
    /// 光环半径，单位米。0表示不是光环。
    /// </summary>
    public readonly float AuraRadius;
   
    public const int __ID__ = 1560804848;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffKey:" + BuffKey + ","
        + "name:" + Name + ","
        + "buffType:" + BuffType + ","
        + "duration:" + Duration + ","
        + "maxStack:" + MaxStack + ","
        + "tickInterval:" + TickInterval + ","
        + "statType:" + StatType + ","
        + "modifierType:" + ModifierType + ","
        + "modifierValue:" + ModifierValue + ","
        + "controlFlags:" + ControlFlags + ","
        + "auraRadius:" + AuraRadius + ","
        + "}";
    }
}
}

