
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Buff : Luban.BeanBase
{
    public Buff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BuffKey = _buf.ReadString();
        Name = _buf.ReadString();
        BuffType = _buf.ReadString();
        Duration = _buf.ReadFloat();
        MaxStack = _buf.ReadInt();
        TickInterval = _buf.ReadFloat();
        StatType = _buf.ReadString();
        ModifierType = _buf.ReadString();
        ModifierValue = _buf.ReadFloat();
        ControlFlags = _buf.ReadString();
        AuraRadius = _buf.ReadFloat();
        AuraBuffId = _buf.ReadInt();
    }

    public static Buff DeserializeBuff(ByteBuf _buf)
    {
        return new skill.Buff(_buf);
    }

    /// <summary>
    /// Buff id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff key.
    /// </summary>
    public readonly string BuffKey;
    /// <summary>
    /// Display name.
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Buff type.
    /// </summary>
    public readonly string BuffType;
    /// <summary>
    /// Duration.
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// Max stack.
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// Tick interval.
    /// </summary>
    public readonly float TickInterval;
    /// <summary>
    /// Stat type.
    /// </summary>
    public readonly string StatType;
    /// <summary>
    /// Modifier type.
    /// </summary>
    public readonly string ModifierType;
    /// <summary>
    /// Modifier value.
    /// </summary>
    public readonly float ModifierValue;
    /// <summary>
    /// Control flags.
    /// </summary>
    public readonly string ControlFlags;
    /// <summary>
    /// Aura radius.
    /// </summary>
    public readonly float AuraRadius;
    /// <summary>
    /// Aura child buff id.
    /// </summary>
    public readonly int AuraBuffId;
   
    public const int __ID__ = 1560804848;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buffKey:" + BuffKey + ","
        + "name:" + Name + ","
        + "buffType:" + BuffType + ","
        + "duration:" + Duration + ","
        + "maxStack:" + MaxStack + ","
        + "tickInterval:" + TickInterval + ","
        + "statType:" + StatType + ","
        + "modifierType:" + ModifierType + ","
        + "modifierValue:" + ModifierValue + ","
        + "controlFlags:" + ControlFlags + ","
        + "auraRadius:" + AuraRadius + ","
        + "auraBuffId:" + AuraBuffId + ","
        + "}";
    }
}
}

