
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Effect : Luban.BeanBase
{
    public Effect(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EffectType = _buf.ReadString();
        Value = _buf.ReadFloat();
        ValueType = _buf.ReadString();
        BuffId = _buf.ReadInt();
        Duration = _buf.ReadFloat();
        Radius = _buf.ReadFloat();
        KnockbackDistance = _buf.ReadFloat();
        ControlType = _buf.ReadString();
        StatType = _buf.ReadString();
        ModifierType = _buf.ReadString();
        ModifierValue = _buf.ReadFloat();
    }

    public static Effect DeserializeEffect(ByteBuf _buf)
    {
        return new skill.Effect(_buf);
    }

    /// <summary>
    /// Effect id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Effect type.
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// Value.
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// Value type.
    /// </summary>
    public readonly string ValueType;
    /// <summary>
    /// Buff id.
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// Duration.
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// Radius.
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// Knockback distance.
    /// </summary>
    public readonly float KnockbackDistance;
    /// <summary>
    /// Control type.
    /// </summary>
    public readonly string ControlType;
    /// <summary>
    /// Stat type.
    /// </summary>
    public readonly string StatType;
    /// <summary>
    /// Modifier type.
    /// </summary>
    public readonly string ModifierType;
    /// <summary>
    /// Modifier value.
    /// </summary>
    public readonly float ModifierValue;
   
    public const int __ID__ = 1061909486;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "effectType:" + EffectType + ","
        + "value:" + Value + ","
        + "valueType:" + ValueType + ","
        + "buffId:" + BuffId + ","
        + "duration:" + Duration + ","
        + "radius:" + Radius + ","
        + "knockbackDistance:" + KnockbackDistance + ","
        + "controlType:" + ControlType + ","
        + "statType:" + StatType + ","
        + "modifierType:" + ModifierType + ","
        + "modifierValue:" + ModifierValue + ","
        + "}";
    }
}
}

