
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Effect : Luban.BeanBase
{
    public Effect(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        EffectType = _buf.ReadString();
        Value = _buf.ReadFloat();
        ValueType = _buf.ReadString();
        BuffId = _buf.ReadInt();
        Duration = _buf.ReadFloat();
        Radius = _buf.ReadFloat();
        KnockbackDistance = _buf.ReadFloat();
        ControlType = _buf.ReadString();
        StatType = _buf.ReadString();
        ModifierType = _buf.ReadString();
        ModifierValue = _buf.ReadFloat();
    }

    public static Effect DeserializeEffect(ByteBuf _buf)
    {
        return new skill.Effect(_buf);
    }

    /// <summary>
    /// 效果ID。被 skill.xlsx 的 effectId 引用。
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果类型。当前 Damage=造成伤害；后续可扩展 Heal/AddBuff/Knockback/Stun。
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// 效果数值。Damage 时表示伤害数值。
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 数值类型。Flat=固定值；后续可扩展 AttackPercent/MaxHpPercent 等。
    /// </summary>
    public readonly string ValueType;
    /// <summary>
    /// 关联Buff ID。0表示不附加Buff；非0时指向 buff.xlsx。
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// 效果持续时间，单位秒。瞬时伤害填0；持续效果可填持续秒数。
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 范围半径，单位米。0表示单体；大于0可作为AOE半径。
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 击退距离，单位米。0表示不击退。
    /// </summary>
    public readonly float KnockbackDistance;
    /// <summary>
    /// 控制类型。None/Stun/Slow/Silence 等，当前原型先用 None。
    /// </summary>
    public readonly string ControlType;
    /// <summary>
    /// 属性类型。None/Attack/MoveSpeed/CastSpeed 等，给属性修改类效果用。
    /// </summary>
    public readonly string StatType;
    /// <summary>
    /// 修改方式。None/Add/Percent/Mul 等，给属性修改类效果用。
    /// </summary>
    public readonly string ModifierType;
    /// <summary>
    /// 修改值。比如减速30%可以约定 modifierType=Percent，modifierValue=-0.3。
    /// </summary>
    public readonly float ModifierValue;
   
    public const int __ID__ = 1061909486;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "effectType:" + EffectType + ","
        + "value:" + Value + ","
        + "valueType:" + ValueType + ","
        + "buffId:" + BuffId + ","
        + "duration:" + Duration + ","
        + "radius:" + Radius + ","
        + "knockbackDistance:" + KnockbackDistance + ","
        + "controlType:" + ControlType + ","
        + "statType:" + StatType + ","
        + "modifierType:" + ModifierType + ","
        + "modifierValue:" + ModifierValue + ","
        + "}";
    }
}
}

