
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Projectile : Luban.BeanBase
{
    public Projectile(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ProjectileKey = _buf.ReadString();
        Speed = _buf.ReadFloat();
        HitRadius = _buf.ReadFloat();
        MaxLifetime = _buf.ReadFloat();
        ProjectilePrefabPath = _buf.ReadString();
        MuzzlePrefabPath = _buf.ReadString();
        ImpactPrefabPath = _buf.ReadString();
        FallbackColor = _buf.ReadString();
    }

    public static Projectile DeserializeProjectile(ByteBuf _buf)
    {
        return new skill.Projectile(_buf);
    }

    /// <summary>
    /// 投射物ID。被 skill.xlsx 的 projectileId 引用。
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 投射物Key。程序/日志识别用。
    /// </summary>
    public readonly string ProjectileKey;
    /// <summary>
    /// 飞行速度，单位米/秒。数值越大飞得越快。
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 命中半径，单位米。原型一般 0.2 到 0.5。
    /// </summary>
    public readonly float HitRadius;
    /// <summary>
    /// 最大存活时间，单位秒。超过后自动销毁，避免特效残留。
    /// </summary>
    public readonly float MaxLifetime;
    /// <summary>
    /// 飞行中特效Prefab路径。Blink资源先放在 ThirdParty 下引用。
    /// </summary>
    public readonly string ProjectilePrefabPath;
    /// <summary>
    /// 出手/枪口/施法点特效Prefab路径。可以为空。
    /// </summary>
    public readonly string MuzzlePrefabPath;
    /// <summary>
    /// 命中特效Prefab路径。可以为空。
    /// </summary>
    public readonly string ImpactPrefabPath;
    /// <summary>
    /// Prefab加载失败时的备用颜色，HTML颜色格式，例如 #40C7FFFF。
    /// </summary>
    public readonly string FallbackColor;
   
    public const int __ID__ = 669715910;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "projectileKey:" + ProjectileKey + ","
        + "speed:" + Speed + ","
        + "hitRadius:" + HitRadius + ","
        + "maxLifetime:" + MaxLifetime + ","
        + "projectilePrefabPath:" + ProjectilePrefabPath + ","
        + "muzzlePrefabPath:" + MuzzlePrefabPath + ","
        + "impactPrefabPath:" + ImpactPrefabPath + ","
        + "fallbackColor:" + FallbackColor + ","
        + "}";
    }
}
}

