
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Projectile : Luban.BeanBase
{
    public Projectile(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ProjectileKey = _buf.ReadString();
        Speed = _buf.ReadFloat();
        HitRadius = _buf.ReadFloat();
        MaxLifetime = _buf.ReadFloat();
        ProjectilePrefabPath = _buf.ReadString();
        MuzzlePrefabPath = _buf.ReadString();
        ImpactPrefabPath = _buf.ReadString();
        FallbackColor = _buf.ReadString();
    }

    public static Projectile DeserializeProjectile(ByteBuf _buf)
    {
        return new skill.Projectile(_buf);
    }

    /// <summary>
    /// Projectile id. 0 means none.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Projectile key.
    /// </summary>
    public readonly string ProjectileKey;
    /// <summary>
    /// Speed.
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// Hit radius.
    /// </summary>
    public readonly float HitRadius;
    /// <summary>
    /// Max lifetime.
    /// </summary>
    public readonly float MaxLifetime;
    /// <summary>
    /// Projectile prefab path.
    /// </summary>
    public readonly string ProjectilePrefabPath;
    /// <summary>
    /// Muzzle prefab path.
    /// </summary>
    public readonly string MuzzlePrefabPath;
    /// <summary>
    /// Impact prefab path.
    /// </summary>
    public readonly string ImpactPrefabPath;
    /// <summary>
    /// Fallback color.
    /// </summary>
    public readonly string FallbackColor;
   
    public const int __ID__ = 669715910;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "projectileKey:" + ProjectileKey + ","
        + "speed:" + Speed + ","
        + "hitRadius:" + HitRadius + ","
        + "maxLifetime:" + MaxLifetime + ","
        + "projectilePrefabPath:" + ProjectilePrefabPath + ","
        + "muzzlePrefabPath:" + MuzzlePrefabPath + ","
        + "impactPrefabPath:" + ImpactPrefabPath + ","
        + "fallbackColor:" + FallbackColor + ","
        + "}";
    }
}
}

