
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SkillKey = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        TargetType = _buf.ReadString();
        EffectId = _buf.ReadInt();
        ProjectileId = _buf.ReadInt();
        Cooldown = _buf.ReadFloat();
        Range = _buf.ReadFloat();
        AnimationKey = _buf.ReadString();
        SyncEventKey = _buf.ReadString();
    }

    public static Skill DeserializeSkill(ByteBuf _buf)
    {
        return new skill.Skill(_buf);
    }

    /// <summary>
    /// 技能ID。必须唯一；同步、存档、日志都用这个稳定ID。
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 程序用Key。建议英文小写，下划线分隔；不要随意改已上线Key。
    /// </summary>
    public readonly string SkillKey;
    /// <summary>
    /// 技能显示名。UI和调试日志给人看的名字。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能描述。策划备注/UI描述都可以先写这里。
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 目标类型。当前支持 EnemySingle：敌方单体。后续可扩展 Self/Ally/AOE。
    /// </summary>
    public readonly string TargetType;
    /// <summary>
    /// 效果ID。指向 effect.xlsx，决定伤害、治疗、控制、加Buff等逻辑效果。
    /// </summary>
    public readonly int EffectId;
    /// <summary>
    /// 投射物ID。指向 projectile.xlsx，决定飞行速度、特效Prefab、命中特效。
    /// </summary>
    public readonly int ProjectileId;
    /// <summary>
    /// 冷却时间，单位秒。AI自动战斗会按这个判断能不能释放。
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 施法距离，单位米。目标超出范围时会先靠近。
    /// </summary>
    public readonly float Range;
    /// <summary>
    /// 动画Key。当前原型用 Attack1，后续通过配置映射到具体动画片段。
    /// </summary>
    public readonly string AnimationKey;
    /// <summary>
    /// 同步事件Key。联机时用于表达这次释放技能是什么事件。
    /// </summary>
    public readonly string SyncEventKey;
   
    public const int __ID__ = 1155715156;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skillKey:" + SkillKey + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "targetType:" + TargetType + ","
        + "effectId:" + EffectId + ","
        + "projectileId:" + ProjectileId + ","
        + "cooldown:" + Cooldown + ","
        + "range:" + Range + ","
        + "animationKey:" + AnimationKey + ","
        + "syncEventKey:" + SyncEventKey + ","
        + "}";
    }
}
}

