
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SkillKey = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        TargetType = _buf.ReadString();
        DefaultLevel = _buf.ReadInt();
        AnimationKey = _buf.ReadString();
        SyncEventKey = _buf.ReadString();
        ResourceType = _buf.ReadString();
        CastMode = _buf.ReadString();
        TargetRule = _buf.ReadString();
        ThreatMultiplier = _buf.ReadFloat();
    }

    public static Skill DeserializeSkill(ByteBuf _buf)
    {
        return new skill.Skill(_buf);
    }

    /// <summary>
    /// Stable skill id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Program key.
    /// </summary>
    public readonly string SkillKey;
    /// <summary>
    /// Display name.
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Description.
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// Target type.
    /// </summary>
    public readonly string TargetType;
    /// <summary>
    /// Default level.
    /// </summary>
    public readonly int DefaultLevel;
    /// <summary>
    /// Animation key.
    /// </summary>
    public readonly string AnimationKey;
    /// <summary>
    /// Sync event key.
    /// </summary>
    public readonly string SyncEventKey;
    /// <summary>
    /// Resource type.
    /// </summary>
    public readonly string ResourceType;
    /// <summary>
    /// Cast mode.
    /// </summary>
    public readonly string CastMode;
    /// <summary>
    /// Target rule.
    /// </summary>
    public readonly string TargetRule;
    /// <summary>
    /// Threat multiplier.
    /// </summary>
    public readonly float ThreatMultiplier;
   
    public const int __ID__ = 1155715156;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skillKey:" + SkillKey + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "targetType:" + TargetType + ","
        + "defaultLevel:" + DefaultLevel + ","
        + "animationKey:" + AnimationKey + ","
        + "syncEventKey:" + SyncEventKey + ","
        + "resourceType:" + ResourceType + ","
        + "castMode:" + CastMode + ","
        + "targetRule:" + TargetRule + ","
        + "threatMultiplier:" + ThreatMultiplier + ","
        + "}";
    }
}
}

