
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class SkillLevel : Luban.BeanBase
{
    public SkillLevel(ByteBuf _buf)
    {
        Id = _buf.ReadInt();
        SkillId = _buf.ReadInt();
        Level = _buf.ReadInt();
        ProjectileId = _buf.ReadInt();
        Cooldown = _buf.ReadFloat();
        Range = _buf.ReadFloat();
        ProjectileSpeed = _buf.ReadFloat();
        FallbackColor = _buf.ReadString();
    }

    public static SkillLevel DeserializeSkillLevel(ByteBuf _buf)
    {
        return new skill.SkillLevel(_buf);
    }

    /// <summary>
    /// Level row id.
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Skill id.
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// Level.
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// Projectile id. 0 means none.
    /// </summary>
    public readonly int ProjectileId;
    /// <summary>
    /// Cooldown seconds.
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// Cast range or radius.
    /// </summary>
    public readonly float Range;
    /// <summary>
    /// Projectile speed.
    /// </summary>
    public readonly float ProjectileSpeed;
    /// <summary>
    /// Fallback color.
    /// </summary>
    public readonly string FallbackColor;

    public const int __ID__ = -65736816;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skillId:" + SkillId + ","
        + "level:" + Level + ","
        + "projectileId:" + ProjectileId + ","
        + "cooldown:" + Cooldown + ","
        + "range:" + Range + ","
        + "projectileSpeed:" + ProjectileSpeed + ","
        + "fallbackColor:" + FallbackColor + ","
        + "}";
    }
}
}
