
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class SkillEffect : Luban.BeanBase
{
    public SkillEffect(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SkillId = _buf.ReadInt();
        Order = _buf.ReadInt();
        TriggerPhase = _buf.ReadString();
        EffectId = _buf.ReadInt();
    }

    public static SkillEffect DeserializeSkillEffect(ByteBuf _buf)
    {
        return new skill.SkillEffect(_buf);
    }

    /// <summary>
    /// 技能效果关系ID。必须唯一。
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能ID。指向 skill.xlsx。
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// 效果执行顺序。数值小的先执行。
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 触发阶段。OnCast/OnHit/OnTick/OnExpire 等。当前示例用 OnHit。
    /// </summary>
    public readonly string TriggerPhase;
    /// <summary>
    /// 效果ID。指向 effect.xlsx。
    /// </summary>
    public readonly int EffectId;
   
    public const int __ID__ = 2057168645;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skillId:" + SkillId + ","
        + "order:" + Order + ","
        + "triggerPhase:" + TriggerPhase + ","
        + "effectId:" + EffectId + ","
        + "}";
    }
}
}

