
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
/// <summary>
/// Buff预留表：配置持续效果、减速、眩晕、光环、属性加成等。当前原型可以先不改。
/// </summary>
public partial class TbBuff
{
    private readonly System.Collections.Generic.Dictionary<int, skill.Buff> _dataMap;
    private readonly System.Collections.Generic.List<skill.Buff> _dataList;
    
    public TbBuff(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.Buff>(n);
        _dataList = new System.Collections.Generic.List<skill.Buff>(n);
        for(int i = n ; i > 0 ; --i)
        {
            skill.Buff _v;
            _v = global::GameConfig.skill.Buff.DeserializeBuff(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, skill.Buff> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<skill.Buff> DataList => _dataList;

    public skill.Buff GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skill.Buff Get(int key) => _dataMap[key];
    public skill.Buff this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

