
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
/// <summary>
/// ?????????????Buff???????
/// </summary>
public partial class TbEffect
{
    private readonly System.Collections.Generic.Dictionary<int, skill.Effect> _dataMap;
    private readonly System.Collections.Generic.List<skill.Effect> _dataList;
    
    public TbEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.Effect>(n);
        _dataList = new System.Collections.Generic.List<skill.Effect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            skill.Effect _v;
            _v = global::GameConfig.skill.Effect.DeserializeEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, skill.Effect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<skill.Effect> DataList => _dataList;

    public skill.Effect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skill.Effect Get(int key) => _dataMap[key];
    public skill.Effect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

