
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
/// <summary>
/// 投射物表现表：配置技能飞行速度、飞行Prefab、出手特效、命中特效和备用颜色。
/// </summary>
public partial class TbProjectile
{
    private readonly System.Collections.Generic.Dictionary<int, skill.Projectile> _dataMap;
    private readonly System.Collections.Generic.List<skill.Projectile> _dataList;
    
    public TbProjectile(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.Projectile>(n);
        _dataList = new System.Collections.Generic.List<skill.Projectile>(n);
        for(int i = n ; i > 0 ; --i)
        {
            skill.Projectile _v;
            _v = global::GameConfig.skill.Projectile.DeserializeProjectile(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, skill.Projectile> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<skill.Projectile> DataList => _dataList;

    public skill.Projectile GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skill.Projectile Get(int key) => _dataMap[key];
    public skill.Projectile this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

