
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
/// <summary>
/// 技能主表：原型阶段优先编辑这里。配置技能ID、显示名、冷却、距离、动画Key，并引用效果和投射物。
/// </summary>
public partial class TbSkill
{
    private readonly System.Collections.Generic.Dictionary<int, skill.Skill> _dataMap;
    private readonly System.Collections.Generic.List<skill.Skill> _dataList;
    
    public TbSkill(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.Skill>(n);
        _dataList = new System.Collections.Generic.List<skill.Skill>(n);
        for(int i = n ; i > 0 ; --i)
        {
            skill.Skill _v;
            _v = global::GameConfig.skill.Skill.DeserializeSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, skill.Skill> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<skill.Skill> DataList => _dataList;

    public skill.Skill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skill.Skill Get(int key) => _dataMap[key];
    public skill.Skill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

