
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
/// <summary>
/// 高级预留：一个技能多个效果/多个触发阶段时再启用。当前运行时还主要读取 skill.effectId。
/// </summary>
public partial class TbSkillEffect
{
    private readonly System.Collections.Generic.Dictionary<int, skill.SkillEffect> _dataMap;
    private readonly System.Collections.Generic.List<skill.SkillEffect> _dataList;
    
    public TbSkillEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.SkillEffect>(n);
        _dataList = new System.Collections.Generic.List<skill.SkillEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            skill.SkillEffect _v;
            _v = global::GameConfig.skill.SkillEffect.DeserializeSkillEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, skill.SkillEffect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<skill.SkillEffect> DataList => _dataList;

    public skill.SkillEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skill.SkillEffect Get(int key) => _dataMap[key];
    public skill.SkillEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

