
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
/// <summary>
/// ????????? skillId ??? level ???????????????????
/// </summary>
public partial class TbSkillLevel
{
    private readonly System.Collections.Generic.Dictionary<int, skill.SkillLevel> _dataMap;
    private readonly System.Collections.Generic.List<skill.SkillLevel> _dataList;
    
    public TbSkillLevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.SkillLevel>(n);
        _dataList = new System.Collections.Generic.List<skill.SkillLevel>(n);
        for(int i = n ; i > 0 ; --i)
        {
            skill.SkillLevel _v;
            _v = global::GameConfig.skill.SkillLevel.DeserializeSkillLevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, skill.SkillLevel> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<skill.SkillLevel> DataList => _dataList;

    public skill.SkillLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public skill.SkillLevel Get(int key) => _dataMap[key];
    public skill.SkillLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

