
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem 
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    /// <summary>
    /// 技能主表：原型阶段优先编辑这里。配置技能ID、显示名、冷却、距离、动画Key，并引用效果和投射物。
    /// </summary>
    private skill.TbSkill m_TbSkill;
    public skill.TbSkill TbSkill 
    {
        get
        {
            if (m_TbSkill == null)
            {
                m_TbSkill = new skill.TbSkill(defaultLoader("skill_tbskill"));
                m_TbSkill.ResolveRef(this);
            }
            return m_TbSkill;
        }
        set
        {
            m_TbSkill = value;
            m_TbSkill.ResolveRef(this);
        }
    }
    /// <summary>
    /// 高级预留：一个技能多个效果/多个触发阶段时再启用。当前运行时还主要读取 skill.effectId。
    /// </summary>
    private skill.TbSkillEffect m_TbSkillEffect;
    public skill.TbSkillEffect TbSkillEffect 
    {
        get
        {
            if (m_TbSkillEffect == null)
            {
                m_TbSkillEffect = new skill.TbSkillEffect(defaultLoader("skill_tbskilleffect"));
                m_TbSkillEffect.ResolveRef(this);
            }
            return m_TbSkillEffect;
        }
        set
        {
            m_TbSkillEffect = value;
            m_TbSkillEffect.ResolveRef(this);
        }
    }
    /// <summary>
    /// 效果表：配置命中后造成什么逻辑效果，例如伤害、治疗、击退、控制、加Buff。
    /// </summary>
    private skill.TbEffect m_TbEffect;
    public skill.TbEffect TbEffect 
    {
        get
        {
            if (m_TbEffect == null)
            {
                m_TbEffect = new skill.TbEffect(defaultLoader("skill_tbeffect"));
                m_TbEffect.ResolveRef(this);
            }
            return m_TbEffect;
        }
        set
        {
            m_TbEffect = value;
            m_TbEffect.ResolveRef(this);
        }
    }
    /// <summary>
    /// Buff预留表：配置持续效果、减速、眩晕、光环、属性加成等。当前原型可以先不改。
    /// </summary>
    private skill.TbBuff m_TbBuff;
    public skill.TbBuff TbBuff 
    {
        get
        {
            if (m_TbBuff == null)
            {
                m_TbBuff = new skill.TbBuff(defaultLoader("skill_tbbuff"));
                m_TbBuff.ResolveRef(this);
            }
            return m_TbBuff;
        }
        set
        {
            m_TbBuff = value;
            m_TbBuff.ResolveRef(this);
        }
    }
    /// <summary>
    /// 投射物表现表：配置技能飞行速度、飞行Prefab、出手特效、命中特效和备用颜色。
    /// </summary>
    private skill.TbProjectile m_TbProjectile;
    public skill.TbProjectile TbProjectile 
    {
        get
        {
            if (m_TbProjectile == null)
            {
                m_TbProjectile = new skill.TbProjectile(defaultLoader("skill_tbprojectile"));
                m_TbProjectile.ResolveRef(this);
            }
            return m_TbProjectile;
        }
        set
        {
            m_TbProjectile = value;
            m_TbProjectile.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
