
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private item.TbItem m_TbItem;
    public item.TbItem TbItem
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    /// <summary>
    /// ??????????????ID???????????????????? skill_level.xlsx?
    /// </summary>
    private skill.TbSkill m_TbSkill;
    public skill.TbSkill TbSkill
    {
        get
        {
            if (m_TbSkill == null)
            {
                m_TbSkill = new skill.TbSkill(defaultLoader("skill_tbskill"));
                m_TbSkill.ResolveRef(this);
            }
            return m_TbSkill;
        }
        set
        {
            m_TbSkill = value;
            m_TbSkill.ResolveRef(this);
        }
    }
    /// <summary>
    /// ????????? skillId ??? level ???????????????????
    /// </summary>
    private skill.TbSkillLevel m_TbSkillLevel;
    public skill.TbSkillLevel TbSkillLevel
    {
        get
        {
            if (m_TbSkillLevel == null)
            {
                m_TbSkillLevel = new skill.TbSkillLevel(defaultLoader("skill_tbskilllevel"));
                m_TbSkillLevel.ResolveRef(this);
            }
            return m_TbSkillLevel;
        }
        set
        {
            m_TbSkillLevel = value;
            m_TbSkillLevel.ResolveRef(this);
        }
    }
    /// <summary>
    /// ????????? skillId + level + order ???? effect?
    /// </summary>
    private skill.TbSkillEffect m_TbSkillEffect;
    public skill.TbSkillEffect TbSkillEffect
    {
        get
        {
            if (m_TbSkillEffect == null)
            {
                m_TbSkillEffect = new skill.TbSkillEffect(defaultLoader("skill_tbskilleffect"));
                m_TbSkillEffect.ResolveRef(this);
            }
            return m_TbSkillEffect;
        }
        set
        {
            m_TbSkillEffect = value;
            m_TbSkillEffect.ResolveRef(this);
        }
    }
    /// <summary>
    /// ?????????????Buff???????
    /// </summary>
    private skill.TbEffect m_TbEffect;
    public skill.TbEffect TbEffect
    {
        get
        {
            if (m_TbEffect == null)
            {
                m_TbEffect = new skill.TbEffect(defaultLoader("skill_tbeffect"));
                m_TbEffect.ResolveRef(this);
            }
            return m_TbEffect;
        }
        set
        {
            m_TbEffect = value;
            m_TbEffect.ResolveRef(this);
        }
    }
    /// <summary>
    /// Buff???????????????????????
    /// </summary>
    private skill.TbBuff m_TbBuff;
    public skill.TbBuff TbBuff
    {
        get
        {
            if (m_TbBuff == null)
            {
                m_TbBuff = new skill.TbBuff(defaultLoader("skill_tbbuff"));
                m_TbBuff.ResolveRef(this);
            }
            return m_TbBuff;
        }
        set
        {
            m_TbBuff = value;
            m_TbBuff.ResolveRef(this);
        }
    }
    /// <summary>
    /// ??????????????Prefab????????
    /// </summary>
    private skill.TbProjectile m_TbProjectile;
    public skill.TbProjectile TbProjectile
    {
        get
        {
            if (m_TbProjectile == null)
            {
                m_TbProjectile = new skill.TbProjectile(defaultLoader("skill_tbprojectile"));
                m_TbProjectile.ResolveRef(this);
            }
            return m_TbProjectile;
        }
        set
        {
            m_TbProjectile = value;
            m_TbProjectile.ResolveRef(this);
        }
    }
    /// <summary>
    /// Stage config.
    /// </summary>
    private stage.TbStage m_TbStage;
    public stage.TbStage TbStage
    {
        get
        {
            if (m_TbStage == null)
            {
                m_TbStage = new stage.TbStage(defaultLoader("stage_tbstage"));
                m_TbStage.ResolveRef(this);
            }
            return m_TbStage;
        }
        set
        {
            m_TbStage = value;
            m_TbStage.ResolveRef(this);
        }
    }
    /// <summary>
    /// Enemy base config.
    /// </summary>
    private stage.TbEnemy m_TbEnemy;
    public stage.TbEnemy TbEnemy
    {
        get
        {
            if (m_TbEnemy == null)
            {
                m_TbEnemy = new stage.TbEnemy(defaultLoader("stage_tbenemy"));
                m_TbEnemy.ResolveRef(this);
            }
            return m_TbEnemy;
        }
        set
        {
            m_TbEnemy = value;
            m_TbEnemy.ResolveRef(this);
        }
    }
    /// <summary>
    /// Enemy level growth config.
    /// </summary>
    private stage.TbEnemyLevel m_TbEnemyLevel;
    public stage.TbEnemyLevel TbEnemyLevel
    {
        get
        {
            if (m_TbEnemyLevel == null)
            {
                m_TbEnemyLevel = new stage.TbEnemyLevel(defaultLoader("stage_tbenemylevel"));
                m_TbEnemyLevel.ResolveRef(this);
            }
            return m_TbEnemyLevel;
        }
        set
        {
            m_TbEnemyLevel = value;
            m_TbEnemyLevel.ResolveRef(this);
        }
    }
    /// <summary>
    /// Wave spawn config.
    /// </summary>
    private stage.TbWave m_TbWave;
    public stage.TbWave TbWave
    {
        get
        {
            if (m_TbWave == null)
            {
                m_TbWave = new stage.TbWave(defaultLoader("stage_tbwave"));
                m_TbWave.ResolveRef(this);
            }
            return m_TbWave;
        }
        set
        {
            m_TbWave = value;
            m_TbWave.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }

    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
